---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-sync
    mode: controller
  name: service-sync-controller
  namespace: service-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-sync
      mode: controller
  template:
    metadata:
      labels:
        app: service-sync
        mode: controller
    spec:
      serviceAccountName: service-sync
      containers:
      - image: vihangvk/gke-service-sync
        name: controller
        resources: {}
        volumeMounts:
          - name: config
            mountPath: /defaults
      volumes:
        - name: config
          configMap:
              name: service-sync-controller-config