apiVersion: v1
kind: Namespace
metadata:
  name: service-sync
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-sync
  namespace: service-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-sync
  namespace: service-sync
rules:
- apiGroups:
  - "*"
  resources:
    - "services"
    - "endpoints"
  verbs:
    - "get"
    - "watch"
    - "list"
    - "create"
    - "update"
    - "patch"
    - "delete"
- apiGroups:
  - "*"
  resources:
    - "namespaces"
  verbs:
    - "get"
    - "list"
    - "create"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-sync
  namespace: service-sync
subjects:
- kind: ServiceAccount
  name: service-sync
  namespace: service-sync
roleRef:
  kind: ClusterRole
  name: service-sync
  apiGroup: rbac.authorization.k8s.io